In [2]:
import pandas as pd

In [6]:
# Specify the file path
file_path = r'C:\Users\User\Desktop\30-Days-of-Python\data\hacker_news.csv'

# Read the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Display the DataFrame
df

,id,title,url,num_points,num_comments,author,created_at
0,12224879,Interactive Dynamic Video,http://www.interactivedynamicvideo.com/,386,52,ne0phyte,8/4/2016 11:52
1,11964716,Florida DJs May Face Felony for April Fools' W...,http://www.thewire.com/entertainment/2013/04/f...,2,1,vezycash,6/23/2016 22:20
2,11919867,Technology ventures: From Idea to Enterprise,https://www.amazon.com/Technology-Ventures-Ent...,3,1,hswarna,6/17/2016 0:01
3,10301696,Note by Note: The Making of Steinway L1037 (2007),http://www.nytimes.com/2007/11/07/movies/07ste...,8,2,walterbell,9/30/2015 4:12
4,10482257,Title II kills investment? Comcast and other I...,http://arstechnica.com/business/2015/10/comcas...,53,22,Deinos,10/31/2015 9:48
...,...,...,...,...,...,...,...
20094,12379592,How Purism Avoids Intels Active Management Tec...,https://puri.sm/philosophy/how-purism-avoids-i...,10,6,AdmiralAsshat,8/29/2016 2:22
20095,10339284,YC Application Translated and Broken Down,https://medium.com/@zreitano/the-yc-applicatio...,4,1,zreitano,10/6/2015 14:57
20096,10824382,Microkernels are slow and Elvis didn't do no d...,http://blog.darknedgy.net/technology/2016/01/0...,169,132,vezzy-fnord,1/2/2016 0:49
20097,10739875,How Product Hunt really works,https://medium.com/@benjiwheeler/how-product-h...,695,222,brw12,12/15/2015 19:32
20098,11680777,RoboBrowser: Your friendly neighborhood web sc...,https://github.com/jmcarp/robobrowser,182,58,pmoriarty,5/12/2016 1:43

In [7]:
# display the first five row 
df.head()

,id,title,url,num_points,num_comments,author,created_at
0,12224879,Interactive Dynamic Video,http://www.interactivedynamicvideo.com/,386,52,ne0phyte,8/4/2016 11:52
1,11964716,Florida DJs May Face Felony for April Fools' W...,http://www.thewire.com/entertainment/2013/04/f...,2,1,vezycash,6/23/2016 22:20
2,11919867,Technology ventures: From Idea to Enterprise,https://www.amazon.com/Technology-Ventures-Ent...,3,1,hswarna,6/17/2016 0:01
3,10301696,Note by Note: The Making of Steinway L1037 (2007),http://www.nytimes.com/2007/11/07/movies/07ste...,8,2,walterbell,9/30/2015 4:12
4,10482257,Title II kills investment? Comcast and other I...,http://arstechnica.com/business/2015/10/comcas...,53,22,Deinos,10/31/2015 9:48

In [8]:
# get the last five row
df.tail()

,id,title,url,num_points,num_comments,author,created_at
20094,12379592,How Purism Avoids Intels Active Management Tec...,https://puri.sm/philosophy/how-purism-avoids-i...,10,6,AdmiralAsshat,8/29/2016 2:22
20095,10339284,YC Application Translated and Broken Down,https://medium.com/@zreitano/the-yc-applicatio...,4,1,zreitano,10/6/2015 14:57
20096,10824382,Microkernels are slow and Elvis didn't do no d...,http://blog.darknedgy.net/technology/2016/01/0...,169,132,vezzy-fnord,1/2/2016 0:49
20097,10739875,How Product Hunt really works,https://medium.com/@benjiwheeler/how-product-h...,695,222,brw12,12/15/2015 19:32
20098,11680777,RoboBrowser: Your friendly neighborhood web sc...,https://github.com/jmcarp/robobrowser,182,58,pmoriarty,5/12/2016 1:43

In [12]:
# Get the "title" column as a Pandas Series
title_series = df['title']
title_series

0                                Interactive Dynamic Video
1        Florida DJs May Face Felony for April Fools' W...
2             Technology ventures: From Idea to Enterprise
3        Note by Note: The Making of Steinway L1037 (2007)
4        Title II kills investment? Comcast and other I...
                               ...
20094    How Purism Avoids Intels Active Management Tec...
20095            YC Application Translated and Broken Down
20096    Microkernels are slow and Elvis didn't do no d...
20097                        How Product Hunt really works
20098    RoboBrowser: Your friendly neighborhood web sc...
Name: title, Length: 20099, dtype: object

In [23]:
# Get the number of rows and columns
num_rows, num_columns = df.shape

print(f"Number of Rows: {num_rows}")
print(f"Number of Columns: {num_columns}")

Number of Rows: 20099
Number of Columns: 7

In [16]:
# filter the titles which contain python
python_titles = df[df['title'].str.contains('Python', case=False)]
print("Titles containing 'Python':")
python_titles['title']

Titles containing 'Python':

102                    From Python to Lua: Why We Switched
103              Ubuntu 16.04 LTS to Ship Without Python 2
144      Create a GUI Application Using Qt and Python i...
196      How I Solved GCHQ's Xmas Card with Python and ...
436      Unikernel Power Comes to Java, Node.js, Go, an...
                               ...
19597    David Beazley  Python Concurrency from the Gro...
19852      Ask HN: How to automate Python apps deployment?
19862                            Moving Away from Python 2
19980                        Python vs. Julia Observations
19998    Show HN: Decorating: Animated pulsed for your ...
Name: title, Length: 160, dtype: object

In [24]:
javascript_titles = df[df['title'].str.contains('JavaScript', case=False)]
print("Titles containing 'JavaScript':")
javascript_titles['title']

Titles containing 'JavaScript':

267       Show HN: Hire JavaScript - Top JavaScript Talent
580      Python integration for the Duktape Javascript ...
811      Ask HN: Are there any projects or compilers wh...
1046     If you write JavaScript tools or libraries, bu...
1093     Rollup.js: A next-generation JavaScript module...
                               ...
19349      Fotorama, a responsive JavaScript photo gallery
19548                   Another Kind of JavaScript Fatigue
19610    Lonely programmer detective uncovers the Mozil...
19885    Ask HN: Best Practices for CSS in a Modern Jav...
20069    Show HN: Parse recipe ingredients using JavaSc...
Name: title, Length: 170, dtype: object

In [26]:
# explore data and make sense of it 
df.shape

(20099, 7)

In [27]:
df.describe()

                 id    num_points  num_comments
count  2.009900e+04  20099.000000  20099.000000
mean   1.131755e+07     50.296632     24.803025
std    6.964531e+05    107.110322     56.108639
min    1.017691e+07      1.000000      1.000000
25%    1.070172e+07      3.000000      1.000000
50%    1.128452e+07      9.000000      3.000000
75%    1.192613e+07     54.000000     21.000000
max    1.257898e+07   2553.000000   1733.000000

In [29]:
df.dtypes

id               int64
title           object
url             object
num_points       int64
num_comments     int64
author          object
created_at      object
dtype: object

In [31]:
for column in df.columns:
    if df[column].dtype == 'object':
        unique_values = df[column].unique()
        print(f"Unique values in {column} column: {unique_values}")

Unique values in title column: ['Interactive Dynamic Video'
 "Florida DJs May Face Felony for April Fools' Water Joke"
 'Technology ventures: From Idea to Enterprise' ...
 "Microkernels are slow and Elvis didn't do no drugs"
 'How Product Hunt really works'
 'RoboBrowser: Your friendly neighborhood web scraper']
Unique values in url column: ['http://www.interactivedynamicvideo.com/'
 'http://www.thewire.com/entertainment/2013/04/florida-djs-april-fools-water-joke/63798/'
 'https://www.amazon.com/Technology-Ventures-Enterprise-Thomas-Byers/dp/0073523429'
 ... 'http://blog.darknedgy.net/technology/2016/01/01/0/'
 'https://medium.com/@benjiwheeler/how-product-hunt-really-works-d8fdcda1da74'
 'https://github.com/jmcarp/robobrowser']
Unique values in author column: ['ne0phyte' 'vezycash' 'hswarna' ... 'mynameisvlad' 'zreitano' 'brw12']
Unique values in created_at column: ['8/4/2016 11:52' '6/23/2016 22:20' '6/17/2016 0:01' ... '1/2/2016 0:49'
 '12/15/2015 19:32' '5/12/2016 1:43']

In [32]:
print("Count of unique values in each column:")
df.nunique()

Count of unique values in each column:

id              20099
title           19957
url             17480
num_points        623
num_comments      390
author          10382
created_at      19702
dtype: int64

In [33]:
print("Number of missing values in each column:")
df.isnull().sum()

Number of missing values in each column:

id                 0
title              0
url             2440
num_points         0
num_comments       0
author             0
created_at         0
dtype: int64

In [34]:
# Drop rows with missing values
df_cleaned = df.dropna()
df_cleaned

,id,title,url,num_points,num_comments,author,created_at
0,12224879,Interactive Dynamic Video,http://www.interactivedynamicvideo.com/,386,52,ne0phyte,8/4/2016 11:52
1,11964716,Florida DJs May Face Felony for April Fools' W...,http://www.thewire.com/entertainment/2013/04/f...,2,1,vezycash,6/23/2016 22:20
2,11919867,Technology ventures: From Idea to Enterprise,https://www.amazon.com/Technology-Ventures-Ent...,3,1,hswarna,6/17/2016 0:01
3,10301696,Note by Note: The Making of Steinway L1037 (2007),http://www.nytimes.com/2007/11/07/movies/07ste...,8,2,walterbell,9/30/2015 4:12
4,10482257,Title II kills investment? Comcast and other I...,http://arstechnica.com/business/2015/10/comcas...,53,22,Deinos,10/31/2015 9:48
...,...,...,...,...,...,...,...
20094,12379592,How Purism Avoids Intels Active Management Tec...,https://puri.sm/philosophy/how-purism-avoids-i...,10,6,AdmiralAsshat,8/29/2016 2:22
20095,10339284,YC Application Translated and Broken Down,https://medium.com/@zreitano/the-yc-applicatio...,4,1,zreitano,10/6/2015 14:57
20096,10824382,Microkernels are slow and Elvis didn't do no d...,http://blog.darknedgy.net/technology/2016/01/0...,169,132,vezzy-fnord,1/2/2016 0:49
20097,10739875,How Product Hunt really works,https://medium.com/@benjiwheeler/how-product-h...,695,222,brw12,12/15/2015 19:32
20098,11680777,RoboBrowser: Your friendly neighborhood web sc...,https://github.com/jmcarp/robobrowser,182,58,pmoriarty,5/12/2016 1:43